apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: devops-toolkit
spec:
  forProvider:
    initialClusterVersion: "1.20"
    location: us-central1
    networkConfig:
      enableIntraNodeVisibility: true
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    addonsConfig:
      gcePersistentDiskCsiDriverConfig:
        enabled: true
    network: "limu-private-vpc"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: gke-conn

---

apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: devops-toolkit
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 3
      minNodeCount: 1
    management:
      autoUpgrade: false
    clusterRef:
      name: devops-toolkit
    config:
      preemptible: true
      machineType: e2-standard-2
      sandboxConfig:
        type: gvisor
      diskSizeGb: 120
      diskType: pd-ssd
      imageType: cos_containerd
      labels:
        test-label: crossplane-created
      oauthScopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"
      - "https://www.googleapis.com/auth/cloud-platform"
    initialNodeCount: 1
    locations:
      - "us-central1-a"
      - "us-central1-b"
      - "us-central1-c"
