apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: devops-db
  namespace: production
spec:
  forProvider:
    region: us-central1
    settings:
      tier: db-custom-1-3840
      dataDiskSizeGb: 20
