apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: devops-toolkit/app
    repoURL: https://github.com/prashasta/combine-infra-services-apps
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://104.197.242.165
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
